CREATE TABLE [dbo].[PERSON]
(
	PERSON_ID INT NOT NULL IDENTITY(1,1),
	FIRST_NAME NVARCHAR(32) NOT NULL,
	LAST_NAME NVARCHAR(32) NOT NULL,
	EMAIL NVARCHAR(256) NOT NULL
	CONSTRAINT PK_PERSON PRIMARY KEY CLUSTERED (PERSON_ID)
)
