CREATE PROCEDURE [open].[GET_PERSON]
(
	/*Returns Json*/
	/*Single Result*/
	@PERSON_ID INT,

	@SQL_ERROR_ID BIGINT OUTPUT,
	@MESSAGE_RESULT VARCHAR(256) OUTPUT
)
AS
BEGIN

	SET NOCOUNT ON;

	IF @PERSON_ID IS NULL THROW 50001, '@PERSON_ID', 1;
	
	DECLARE @RESULT_TABLE TABLE
	(
		PERSON_ID INT
	)

	BEGIN TRY

		SELECT
			PERSON_ID personId,
			FIRST_NAME firstName,
			LAST_NAME lastName,
			EMAIL email
		FROM
			dbo.PERSON
		WHERE
			PERSON_ID = @PERSON_ID
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER

		RETURN 200;

	END TRY
	BEGIN CATCH

		SET @SQL_ERROR_ID = 21;
		SET @MESSAGE_RESULT = (SELECT 500 AS messageId FOR JSON PATH, WITHOUT_ARRAY_WRAPPER);
		RETURN 500;

	END CATCH

END;