CREATE PROCEDURE [open].[PUT_PERSON]
/*Returns Json*/
	/*Single Result*/
	@PERSON_ID int,
	@FIRST_NAME nvarchar(32),
    @LAST_NAME nvarchar(32),
    @EMAIL nvarchar(256),

	@SQL_ERROR_ID BIGINT OUTPUT,
	@MESSAGE_RESULT VARCHAR(256) OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

	IF @PERSON_ID IS NULL THROW 50001, '@PERSON_ID', 1;
	IF @FIRST_NAME IS NULL THROW 50001, '@FIRST_NAME', 1;
	IF @LAST_NAME IS NULL THROW 50001, '@LAST_NAME', 1;
	IF @EMAIL IS NULL THROW 50001, '@EMAIL', 1;

	DECLARE @RESULT_TABLE TABLE
	(
		PERSON_ID INT
	)

	BEGIN TRY

		IF EXISTS(SELECT 1 FROM dbo.PERSON WHERE EMAIL = @EMAIL AND PERSON_ID != @PERSON_ID )
		BEGIN
			SET @MESSAGE_RESULT = (SELECT 999 AS messageId, 'SOME GENERIC MESSAGE' AS messageText FOR JSON PATH, WITHOUT_ARRAY_WRAPPER);
			RETURN 409
		END

		UPDATE PERSON SET
			[FIRST_NAME] = @FIRST_NAME,
			LAST_NAME = @LAST_NAME,
			EMAIL = @EMAIL
		WHERE
			PERSON_ID = @PERSON_ID

		RETURN 200;

	END TRY
	BEGIN CATCH

		SET @SQL_ERROR_ID = 21;
		SET @MESSAGE_RESULT = (SELECT 500 AS messageId FOR JSON PATH, WITHOUT_ARRAY_WRAPPER);
		RETURN 500;

	END CATCH

END;
